### ISSUE TITLE
XML error from getting a new version of deck 

### ISSUE THREAD

**Issue by leadingmore** [HearthStats/hearthstats#523]
Log from HDT.  It was reported to HDT first but it is marked as Hearthstats issue there.

9:07:31 AM|Info|HearthStatsManager.SyncAsync >> Checking HearthStats for new decks...
9:07:31 AM|Info|HearthStatsManager.DownloadDecksAsync >> trying to download decks
9:07:31 AM|Info|HearthStatsAPI.GetDecksAsync >> getting decks since 0
9:07:46 AM|Info|HearthStatsManager.SyncAsync >> Checking for new versions...
9:07:46 AM|Info|HearthStatsManager.SyncAsync >> saved 1 new versions (1.2.0.0) to Leeroy Miracle (Rogue)
9:07:46 AM|Error|XmlManager.Save >> Error saving file: C:\Users\XXXXXXX\AppData\Roaming\HearthstoneDeckTracker\PlayerDecks.xml
**System.InvalidOperationException: There was an error generating the XML document. ---> System.InvalidOperationException: A circular reference was detected while serializing an object of type Hearthstone_Deck_Tracker.Hearthstone.Deck.**
   at System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(String name, String ns, Object o, Boolean writePrefixed, XmlSerializerNamespaces xmlns)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterDeckList.Write8_Deck(String n, String ns, Deck o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterDeckList.Write8_Deck(String n, String ns, Deck o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterDeckList.Write10_DeckList(String n, String ns, DeckList o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterDeckList.Write11_Decks(Object o)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at System.Xml.Serialization.XmlSerializer.Serialize(TextWriter textWriter, Object o, XmlSerializerNamespaces namespaces)
   at Hearthstone_Deck_Tracker.XmlManager`1.Save(String path, Object obj)
9:07:46 AM|Info|HearthStatsManager.SyncAsync >> Checking for edited decks...
9:07:46 AM|Info|HearthStatsManager.SyncAsync >> edited latest version of Leeroy Miracle (Rogue)
9:07:46 AM|Error|XmlManager.Save >> Error saving file: C:\Users\XXXXXXX\AppData\Roaming\HearthstoneDeckTracker\PlayerDecks.xml
**System.InvalidOperationException: There was an error generating the XML document. ---> System.InvalidOperationException: A circular reference was detected while serializing an object of type Hearthstone_Deck_Tracker.Hearthstone.Deck.**
   at System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(String name, String ns, Object o, Boolean writePrefixed, XmlSerializerNamespaces xmlns)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterDeckList.Write8_Deck(String n, String ns, Deck o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterDeckList.Write8_Deck(String n, String ns, Deck o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterDeckList.Write10_DeckList(String n, String ns, DeckList o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterDeckList.Write11_Decks(Object o)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at System.Xml.Serialization.XmlSerializer.Serialize(TextWriter textWriter, Object o, XmlSerializerNamespaces namespaces)
   at Hearthstone_Deck_Tracker.XmlManager`1.Save(String path, Object obj)
9:07:46 AM|Info|HearthStatsManager.SyncAsync >> edited 1 decks

**Comment by riQQ** [comment]
Probably a HDT issue, not a Hearthstats issue.
